/**
 * `@mycel/insight` — the evidence loop.
 *
 * A founder's product is generated by an agent. Today, once it is live, that agent is blind: it can
 * read its own code and nothing about what happened when a real customer met it. So the next
 * iteration is guesswork dressed up as judgement, and "AI-native" means "an AI typed it once".
 *
 * This package closes that. The product declares a funnel, the client reports steps under consent,
 * the kernel rolls them up per project, and `GET /v1/insight/summary` hands the agent a terse,
 * structured answer to "which step is losing people, and what changed since last week" — shaped to
 * be the INPUT TO A TASK, not a chart for a human to interpret.
 *
 * What it deliberately cannot do: identify a person, store an IP, keep a URL, or hold anything a
 * customer typed. See `redact.ts`. Those are not settings.
 *
 * A note on entry points. This barrel re-exports everything, including the client, for the
 * convenience of tests and of code that already knows it wants it. The PROVIDER does not use it:
 * `next.tsx` imports `./client` dynamically and only after consent is granted, so an unconsented
 * visitor never downloads the tracking code at all. If you are wiring this into a product, import
 * `@mycel/insight/next` and let it do that; reaching for `initInsight` from a top-level module
 * puts the client in the initial bundle and quietly loses that property.
 */
export { defineFunnel, analyseFunnel, stepIndex } from "./funnel";
export type { FunnelDefinition, FunnelReport, FunnelStepReport } from "./funnel";
export { readConsent, setConsent, onConsentChange, forgetEverything } from "./consent";
export type { Consent } from "./consent";
export { redactPath, redactProps, redactPropValue, redactEventName, isSensitiveKey } from "./redact";
export { LIMITS, INSIGHT_VERSION, RESERVED } from "./types";
export type { InsightBatch, InsightConfig, InsightEvent, InsightPropValue } from "./types";
export type { Insight } from "./client";
export { createInsight, initInsight, getInsight, track } from "./client";
