// ═══ WHAT THE FINISHED THING LOOKS LIKE ═══
//
// An authored service gets rules, procedures, and — since `identitiesToChecks` — machine gates on
// its arithmetic. It has never been told what the OBJECT looks like.
//
// That is measurable rather than theoretical. A real run of `write_post` for a landscaping firm on
// 3 September produced 688 words with no marketing slop, no invented figures, a correct derivation
// of distribution uniformity, and an explicit refusal to state a price it had not been given. The
// judgement was excellent. What came back was a text blob the founder would have to format before
// anyone could send it.
//
// ═══ THE LITERATURE SAYS THIS IS A NAMED GAP, NOT OUR BUG ═══
//
// DocReward (arXiv, 2026) opens on exactly this: "Recent agentic workflows automate professional
// document generation but focus narrowly on textual quality, overlooking structural and stylistic
// professionalism, which is equally critical for readability." Their remedy is a reward model that
// is deliberately TEXTUAL-QUALITY-AGNOSTIC — structure judged without being confounded by content.
//
// We already have that separation for artefacts: `design-lint.ts` judges an HTML document's
// structure without any opinion about whether its claims are true, and `shipFaults` judges the
// arithmetic without any opinion about how it is laid out. Two gates, two questions. What was
// missing is the instruction that makes the structural half achievable at all.
//
// ═══ AND WHY THIS IS A SKELETON RATHER THAN A WORKED EXAMPLE ═══
//
// The obvious move is to author a specimen deliverable — a whole finished report with invented
// findings — the way `wedges/*/exemplars/` ships one for the trades we wrote by hand.
//
// "When Correct Demonstrations Hurt: Rethinking the Role of Exemplars in In-Context Learning"
// (arXiv, 2026) argues against it, and the mechanism it names is the one that would bite us:
// "correctness does not guarantee exemplar utility, and some correct demonstrations can even
// reduce ICL accuracy". They call the failure CONTEXTUAL EVIDENCE SHIFT — a demonstration changes
// "the effective mixture of evidence used by the model for contextual inference", and it worsens
// with harder tasks. A finished specimen full of invented findings is a large pile of confident,
// plausible, wrong evidence about the very engagement the run is trying to describe, sitting in
// context next to the real facts.
//
// The shipped exemplars survive that because a human wrote them and they carry a loud warning. An
// AUTOGENERATED one would carry the same warning and none of the judgement.
//
// So: the shape, and no specimen content. Section order, what each section must contain, how deep
// it goes, and what the artefact must be — with nothing importable. It teaches structure, which is
// the half that is missing, and imports no evidence, which is the half that hurts.

import type { TradeIdentity } from "./trade-identities";

/**
 * The mounted filename, in ONE place.
 *
 * Two callers write this page (the runtime for shipped wedges, `wedgeauthor` for authored ones)
 * and the deliver prompt points at it by name. Three string literals for one file is how a mount
 * and its pointer drift apart, and a pointer to a file that is not there teaches the model that
 * the index lies.
 */
export const SHAPE_SKILL_FILE = "the-shape-of-the-finished-work.md";

/** One section of the finished artefact. */
export interface ShapeSection {
  /** What a practitioner in this trade calls it. */
  heading: string;
  /** What must be in it — the obligation, not a sentence to copy. */
  must: string;
  /** Roughly how much: "one line", "a short paragraph", "a table". Depth is what prose cannot say. */
  depth: string;
}

export interface DeliverableShape {
  /** The artefact a client actually opens. `document` is the fallback, never the aspiration. */
  format: "document" | "report" | "spreadsheet" | "deck" | "link";
  sections: ShapeSection[];
}

/**
 * The shape as a mounted page, or undefined when the draft did not describe one.
 *
 * Undefined rather than a default: a generic skeleton ("Summary, Findings, Next steps") applied to
 * every trade is worse than none, because it reads as authoritative and is nobody's actual format.
 * A trade whose shape we do not know should get the run's own judgement, not our guess.
 */
export function deliverableShapeAsSkill(
  shape: DeliverableShape | undefined,
  identities: readonly TradeIdentity[] = [],
): string | undefined {
  if (!shape || !Array.isArray(shape.sections) || shape.sections.length === 0) return undefined;
  const sections = shape.sections.filter((s) => s && typeof s.heading === "string" && s.heading.trim());
  if (sections.length === 0) return undefined;

  const lines: string[] = [
    "# The shape of the finished work",
    "",
    "This is what the artefact looks like when it is done. It is a SHAPE, not a sample: there are no",
    "findings here to reuse, because any finding written into this page would be invented, and an",
    "invented figure sitting beside your real ones is the most expensive thing this file could carry.",
    "",
    `The client opens a **${shape.format}**. Produce that, not notes about it. Markdown handed to a`,
    "client is a draft they now have to format themselves, which is the work they were paying to",
    "avoid.",
    "",
    "## Sections, in this order",
    "",
  ];
  for (const [i, s] of sections.entries()) {
    lines.push(`### ${i + 1}. ${s.heading.trim()}`);
    lines.push("");
    if (s.must?.trim()) lines.push(`${s.must.trim()}`);
    if (s.depth?.trim()) lines.push(`_Depth: ${s.depth.trim()}._`);
    lines.push("");
  }

  if (identities.length) {
    lines.push("## What has to reconcile before it ships");
    lines.push("");
    lines.push(
      "These are checked by machine after you finish. A section that presents a total must present",
      "the parts that make it, or the check has nothing to reconcile against and the work is held.",
      "",
    );
    for (const id of identities.slice(0, 6)) {
      if (typeof id?.says === "string" && id.says.trim()) lines.push(`- ${id.says.trim()}`);
    }
    lines.push("");
  }

  lines.push(
    "## The two ways this comes back",
    "",
    "A reader judges a document on whether it is RIGHT and on whether it is READABLE, and those are",
    "separate failures with separate causes. Correct findings in an unstructured wall of text get",
    "read as sloppy work; a beautifully laid out document with one figure that does not reconcile",
    "gets read as dishonest. Satisfy the shape above and the reconciliations above. Neither excuses",
    "the other.",
  );
  return lines.join("\n");
}

/** Parse a `deliverable_shape` off an authored draft, or undefined. Silent on anything malformed. */
export function readDeliverableShape(raw: unknown): DeliverableShape | undefined {
  if (!raw || typeof raw !== "object") return undefined;
  const r = raw as { format?: unknown; sections?: unknown };
  const format = typeof r.format === "string" && ["document", "report", "spreadsheet", "deck", "link"].includes(r.format)
    ? (r.format as DeliverableShape["format"])
    : "document";
  if (!Array.isArray(r.sections)) return undefined;
  const sections: ShapeSection[] = [];
  for (const s of r.sections.slice(0, 12)) {
    if (!s || typeof s !== "object") continue;
    const o = s as { heading?: unknown; must?: unknown; depth?: unknown };
    if (typeof o.heading !== "string" || !o.heading.trim()) continue;
    sections.push({
      heading: o.heading.trim().slice(0, 90),
      must: typeof o.must === "string" ? o.must.trim().slice(0, 400) : "",
      depth: typeof o.depth === "string" ? o.depth.trim().slice(0, 90) : "",
    });
  }
  return sections.length ? { format, sections } : undefined;
}
