// THE RESEARCH KNEW EVERY RULE OF A TRADE AND HAD NEVER SEEN ITS WORK.
//
// `research_service` collects deliverables, steps, price, what the buyer expects, what goes wrong,
// the arithmetic and the mechanics. All of it is the PROCESS. None of it is a specimen, so a run
// could know every rule of a trade and still write a correct document nobody in that trade would
// recognise — the right facts in the wrong object.
//
// This is also the one thing `deliverable-shape.ts` deliberately refuses to invent. Its header cites
// "When Correct Demonstrations Hurt" for why an AUTOGENERATED specimen is dangerous: a pile of
// confident, plausible, wrong evidence beside the real facts. A real published specimen is the
// opposite — it is rung-one evidence, and the reason to go and find one rather than write one.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { researchQuality } from "../src/research-quality";
import { withDraftServiceArsenal } from "../src/skill-arsenal";

const WEDGE = new URL("../../wedges/business-shaper/", import.meta.url).pathname;
const manifest = JSON.parse(readFileSync(`${WEDGE}wedge.json`, "utf8"));
const skill = readFileSync(`${WEDGE}skills/research-a-service.md`, "utf8");
const schema = manifest.task_types.research_service.output_schema.properties;

test("the research asks for real finished work, not only the rules", () => {
  const f = schema.artefact_examples;
  assert.ok(f, "research_service has no field for a specimen");
  assert.deepEqual(f.items.required.sort(), ["source", "what", "why_good"]);
});

test("a specimen must carry WHY it is good, or it teaches nothing", () => {
  // "professional and well laid out" is worth nothing to the run that reads it. The whole value is
  // one concrete property that can be copied.
  assert.ok(schema.artefact_examples.items.required.includes("why_good"));
  assert.match(schema.artefact_examples.items.properties.why_good.description, /is not|not useful|'it is/i);
  assert.match(skill, /One concrete property beats a paragraph of praise/);
});

test("the source must open the artefact, not a page describing one", () => {
  assert.match(schema.artefact_examples.items.properties.source.description, /Not a page describing one/);
  assert.match(schema.artefact_examples.description, /not a sales page about it/);
});

test("an example it could not find is a gap, never a description", () => {
  // The failure this must not have: a plausible specimen the run invented, which the next run copies.
  assert.match(schema.artefact_examples.description, /a described example is a fabrication with a citation attached/i);
  // `\s+` rather than a literal space: the skill is prose wrapped at 100 columns, and a matcher
  // that assumes one line breaks every time somebody reflows a paragraph.
  assert.match(skill, /Describing an example\s+you did not open is a fabrication/);
  assert.match(skill, /leave it empty and say so in `blocked_by`/);
});

test("the skill says where to look, in the same ladder the rest of the job uses", () => {
  const at = skill.indexOf("artefact_examples");
  assert.ok(at > skill.indexOf("## Where to look, in order"), "it belongs after the ladder it depends on");
  assert.match(skill, /Prefer specimens from rung\s+one or two/);
  assert.match(skill, /filetype:pdf/, "a real specimen is usually a file, and the search shape should say so");
});

test("specimens are scored by source like every other finding, for free", () => {
  // `researchQuality` walks any array of objects carrying a `source`. Naming the field `source` —
  // rather than `url` — is what makes a specimen from a regulator outrank one from an agency blog
  // without a line of new scoring code.
  const q = researchQuality({
    reached: true,
    artefact_examples: [
      { what: "model return", source: "https://www.gov.uk/model-return.pdf", why_good: "ties on page one" },
      { what: "agency sample", source: "https://someagency.com/sample", why_good: "has a summary" },
    ],
  });
  assert.equal(q.counts.primary, 1, "a regulator's specimen is rung one");
  assert.equal(q.counts.marketing, 1, "an agency's sample is not");
  assert.equal(q.distinctHosts, 2);
});

test("specimens reach the author with the rest of the research", () => {
  const out = withDraftServiceArsenal(
    { description: "bookkeeping for dentists" },
    {
      reached: true,
      artefact_examples: [
        { what: "HMRC model return", source: "https://www.gov.uk/x.pdf", why_good: "reconciles on page one" },
      ],
    },
  );
  const research = out.research as Record<string, unknown>;
  assert.ok(Array.isArray(research.artefact_examples), "the specimen must survive the seam to the author");
  assert.match(String(out.research_quality && (out.research_quality as any).summary), /standards or trade bodies/);
});
