// GENERATED BY scripts/generate-schema.mjs — DO NOT EDIT.
//
// This file is a VIEW of the DDL in src/*.pg.ts, which is the real schema: this kernel creates its
// own tables at boot and has no migrations directory. Editing here changes nothing about the
// database and will be overwritten; change the CREATE TABLE or ADD COLUMN statement instead and run
// `npm run schema`.
//
// test/schema-is-current.test.ts fails if this file and the DDL disagree.
//
// What it is FOR: a column name that does not exist stops being a runtime error on a query nobody
// ran in staging, and becomes a compile error. Four queries written against this schema in one
// afternoon referenced tasks.output, events.created_at, standing_grants and rules.source — none of
// which exist — and all four typechecked, deployed, and failed against production.
import {
  bigint,
  boolean,
  doublePrecision,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

export const apiKeys = pgTable("api_keys", {
  key: text("key").primaryKey(),
  projectId: text("project_id").notNull(),
  orgId: text("org_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const approvals = pgTable("approvals", {
  approvalId: uuid("approval_id").primaryKey(),
  taskId: uuid("task_id").notNull(),
  action: text("action").notNull(),
  risk: text("risk").notNull(),
  preview: jsonb("preview").notNull(),
  status: text("status").notNull(),
  policyReason: text("policy_reason"),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  edited: boolean("edited").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  decidedAt: timestamp("decided_at", { withTimezone: true }),
});

export const artifacts = pgTable("artifacts", {
  id: uuid("id").primaryKey(),
  taskId: uuid("task_id").notNull(),
  name: text("name").notNull(),
  contentType: text("content_type").notNull(),
  content: text("content").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  encoding: text("encoding").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }),
  source: text("source").notNull(),
  rendersTo: text("renders_to"),
  clientId: text("client_id"),
  uploadedBy: text("uploaded_by"),
});

export const auditHeads = pgTable("audit_heads", {
  projectId: text("project_id").primaryKey(),
  seq: integer("seq").notNull(),
  hash: text("hash").notNull(),
});

export const auditLog = pgTable("audit_log", {
  projectId: text("project_id").notNull(),
  seq: integer("seq").notNull(),
  at: timestamp("at", { withTimezone: true }).notNull(),
  actor: text("actor").notNull(),
  action: text("action").notNull(),
  entity: text("entity").notNull(),
  entityId: text("entity_id").notNull(),
  detail: jsonb("detail").notNull(),
  prevHash: text("prev_hash").notNull(),
  hash: text("hash").notNull(),
});

export const authoredWedges = pgTable("authored_wedges", {
  id: text("id").notNull(),
  projectId: text("project_id").notNull(),
  slug: text("slug").notNull(),
  title: text("title").notNull(),
  manifest: jsonb("manifest").notNull(),
  skills: jsonb("skills").notNull(),
  knowledge: jsonb("knowledge").notNull(),
  status: text("status").notNull(),
  describedAs: text("described_as").notNull(),
  notices: jsonb("notices").notNull(),
  sourceTaskId: text("source_task_id"),
  decidedBy: text("decided_by"),
  decidedAt: timestamp("decided_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const batches = pgTable("batches", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  parentTaskId: text("parent_task_id").notNull(),
  wedge: text("wedge").notNull(),
  caseId: text("case_id"),
  clientId: text("client_id"),
  status: text("status").notNull(),
  joinMode: text("join_mode").notNull(),
  quorum: integer("quorum"),
  childTaskIds: text("child_task_ids").array().notNull(),
  aggregate: jsonb("aggregate"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  joinedAt: timestamp("joined_at", { withTimezone: true }),
});

export const caseWaits = pgTable("case_waits", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id").notNull(),
  caseId: uuid("case_id").notNull(),
  wedge: text("wedge").notNull(),
  reason: text("reason").notNull(),
  condition: jsonb("condition").notNull(),
  resume: jsonb("resume").notNull(),
  status: text("status").notNull(),
  nudgeAt: timestamp("nudge_at", { withTimezone: true }),
  nudgeCount: integer("nudge_count").notNull(),
  maxNudges: integer("max_nudges").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  waitMode: text("wait_mode").notNull(),
  parts: jsonb("parts").notNull(),
  satisfiedBy: text("satisfied_by"),
  satisfiedIndex: integer("satisfied_index"),
  satisfiedAt: timestamp("satisfied_at", { withTimezone: true }),
  resumedTaskId: uuid("resumed_task_id"),
  error: text("error"),
  rearmCount: integer("rearm_count").notNull(),
  rearmedAt: timestamp("rearmed_at", { withTimezone: true }),
  rearmedBy: text("rearmed_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const cases = pgTable("cases", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  wedge: text("wedge").notNull(),
  title: text("title").notNull(),
  clientId: uuid("client_id"),
  stage: text("stage").notNull(),
  status: text("status").notNull(),
  data: jsonb("data").notNull(),
  dueAt: timestamp("due_at", { withTimezone: true }),
  meetingAt: timestamp("meeting_at", { withTimezone: true }),
  history: jsonb("history").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  closedAt: timestamp("closed_at", { withTimezone: true }),
});

export const channels = pgTable("channels", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  connectionId: uuid("connection_id").notNull(),
  kind: text("kind").notNull(),
  address: text("address").notNull(),
  wedge: text("wedge").notNull(),
  taskType: text("task_type").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const clientRequests = pgTable("client_requests", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  clientId: text("client_id").notNull(),
  caseId: text("case_id"),
  threadId: text("thread_id"),
  taskId: text("task_id"),
  kind: text("kind").notNull(),
  ask: text("ask").notNull(),
  detail: text("detail"),
  status: text("status").notNull(),
  dueAt: timestamp("due_at", { withTimezone: true }),
  response: text("response"),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  lastNudgedAt: timestamp("last_nudged_at", { withTimezone: true }),
  nudgeCount: integer("nudge_count").notNull(),
  responseArtifactIds: jsonb("response_artifact_ids"),
  connectionToolkit: text("connection_toolkit"),
  answeredBy: text("answered_by"),
  partyRole: text("party_role"),
  partyLabel: text("party_label"),
  partyEmail: text("party_email"),
});

export const clients = pgTable("clients", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  displayName: text("display_name"),
  handles: jsonb("handles").notNull(),
  metadata: jsonb("metadata").notNull(),
  preferences: jsonb("preferences"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const connections = pgTable("connections", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  kind: text("kind").notNull(),
  name: text("name").notNull(),
  owner: jsonb("owner").notNull(),
  config: jsonb("config").notNull(),
  secretRef: text("secret_ref"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const deliverableVersions = pgTable("deliverable_versions", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  deliverableId: text("deliverable_id").notNull(),
  version: integer("version").notNull(),
  summary: text("summary").notNull(),
  artifactIds: text("artifact_ids").array().notNull(),
  author: text("author"),
  url: text("url"),
  taskId: text("task_id"),
  releasedAt: timestamp("released_at", { withTimezone: true }),
  changeRequest: text("change_request"),
  changeRequestedAt: timestamp("change_requested_at", { withTimezone: true }),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  acceptedNote: text("accepted_note"),
  supersededAt: timestamp("superseded_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const deliverables = pgTable("deliverables", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  caseId: text("case_id").notNull(),
  clientId: text("client_id").notNull(),
  title: text("title").notNull(),
  kind: text("kind").notNull(),
  status: text("status").notNull(),
  currentVersion: integer("current_version").notNull(),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  withdrawnReason: text("withdrawn_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const deployments = pgTable("deployments", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id").notNull(),
  taskId: uuid("task_id"),
  slug: text("slug").notNull(),
  url: text("url").notNull(),
  status: text("status").notNull(),
  buildId: text("build_id"),
  sourceKey: text("source_key"),
  error: text("error"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const events = pgTable("events", {
  taskId: uuid("task_id").notNull(),
  seq: integer("seq").notNull(),
  type: text("type").notNull(),
  data: jsonb("data").notNull(),
  ts: timestamp("ts", { withTimezone: true }).notNull(),
});

export const grants = pgTable("grants", {
  kind: text("kind").notNull(),
  nonce: text("nonce").notNull(),
  payload: jsonb("payload").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const invites = pgTable("invites", {
  id: text("id").primaryKey(),
  orgId: text("org_id").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  invitedBy: text("invited_by").notNull(),
  tokenHash: text("token_hash").notNull(),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const invoiceCounters = pgTable("invoice_counters", {
  projectId: text("project_id").primaryKey(),
  lastNumber: bigint("last_number", { mode: "number" }).notNull(),
});

export const invoiceExternalPayments = pgTable("invoice_external_payments", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  invoiceId: text("invoice_id").notNull(),
  externalId: text("external_id").notNull(),
  amountMinor: bigint("amount_minor", { mode: "number" }).notNull(),
  currency: text("currency").notNull(),
  paidAt: timestamp("paid_at", { withTimezone: true }).notNull(),
  basis: text("basis").notNull(),
  source: text("source").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  method: text("method"),
  reference: text("reference"),
});

export const invoicePaymentChecks = pgTable("invoice_payment_checks", {
  projectId: text("project_id").primaryKey(),
  confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
  attemptedAt: timestamp("attempted_at", { withTimezone: true }).notNull(),
  ok: boolean("ok").notNull(),
  detail: text("detail").notNull(),
});

export const invoiceRetainerPeriods = pgTable("invoice_retainer_periods", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  caseId: text("case_id").notNull(),
  lineId: text("line_id").notNull(),
  periodKey: text("period_key").notNull(),
  periodEnd: text("period_end").notNull(),
  amountMinor: bigint("amount_minor", { mode: "number" }).notNull(),
  currency: text("currency").notNull(),
  claimedAt: timestamp("claimed_at", { withTimezone: true }).notNull(),
  invoiceId: text("invoice_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const invoices = pgTable("invoices", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  clientId: text("client_id").notNull(),
  caseId: text("case_id"),
  number: text("number").notNull(),
  currency: text("currency").notNull(),
  status: text("status").notNull(),
  lines: jsonb("lines").notNull(),
  issueDate: text("issue_date"),
  dueDate: text("due_date"),
  amountPaid: bigint("amount_paid", { mode: "number" }).notNull(),
  paymentLinkUrl: text("payment_link_url"),
  note: text("note"),
  internalNote: text("internal_note"),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  paidAt: timestamp("paid_at", { withTimezone: true }),
  voidedAt: timestamp("voided_at", { withTimezone: true }),
  lastChasedAt: timestamp("last_chased_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  paymentClaimedAt: timestamp("payment_claimed_at", { withTimezone: true }),
  paymentClaimNote: text("payment_claim_note"),
});

export const knowledge = pgTable("knowledge", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  wedge: text("wedge").notNull(),
  name: text("name").notNull(),
  content: text("content").notNull(),
  kind: text("kind").notNull(),
  source: text("source").notNull(),
  metadata: jsonb("metadata").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const knowledgeGaps = pgTable("knowledge_gaps", {
  id: text("id").notNull(),
  projectId: text("project_id").notNull(),
  wedge: text("wedge").notNull(),
  question: text("question").notNull(),
  fallback: text("fallback"),
  hits: integer("hits").notNull(),
  taskIds: text("task_ids").array().notNull(),
  status: text("status").notNull(),
  firstSeen: timestamp("first_seen", { withTimezone: true }).notNull(),
  lastSeen: timestamp("last_seen", { withTimezone: true }).notNull(),
});

export const members = pgTable("members", {
  id: text("id").primaryKey(),
  orgId: text("org_id").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  salt: text("salt").notNull(),
  hash: text("hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  lastProvider: text("last_provider"),
  providers: jsonb("providers").notNull(),
  resetHash: text("reset_hash"),
  resetExpires: bigint("reset_expires", { mode: "number" }),
  prefs: jsonb("prefs"),
  emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
  verifyHash: text("verify_hash"),
  verifyExpires: bigint("verify_expires", { mode: "number" }),
  verifySends: jsonb("verify_sends"),
});

export const messages = pgTable("messages", {
  id: uuid("id").primaryKey(),
  threadId: uuid("thread_id").notNull(),
  direction: text("direction").notNull(),
  author: text("author").notNull(),
  body: text("body").notNull(),
  status: text("status"),
  taskId: uuid("task_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const observations = pgTable("observations", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  wedge: text("wedge").notNull(),
  taskType: text("task_type").notNull(),
  clientId: text("client_id"),
  kind: text("kind").notNull(),
  subject: text("subject"),
  taskId: text("task_id"),
  at: timestamp("at", { withTimezone: true }).notNull(),
});

export const orgs = pgTable("orgs", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  plan: text("plan").notNull(),
  planStatus: text("plan_status").notNull(),
  billingRef: text("billing_ref"),
  planRenewsAt: timestamp("plan_renews_at", { withTimezone: true }),
  lastDigestAt: timestamp("last_digest_at", { withTimezone: true }),
  referralCode: text("referral_code"),
  referredBy: text("referred_by"),
  referralCreditedAt: timestamp("referral_credited_at", { withTimezone: true }),
});

export const partyLinks = pgTable("party_links", {
  hash: text("hash").primaryKey(),
  projectId: text("project_id").notNull(),
  clientId: text("client_id").notNull(),
  requestId: text("request_id").notNull(),
  partyRole: text("party_role").notNull(),
  partyLabel: text("party_label"),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
  used: boolean("used").notNull(),
  usedAt: bigint("used_at", { mode: "number" }),
  sessionToken: text("session_token"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const partySessions = pgTable("party_sessions", {
  token: text("token").primaryKey(),
  projectId: text("project_id").notNull(),
  clientId: text("client_id").notNull(),
  requestId: text("request_id").notNull(),
  partyRole: text("party_role").notNull(),
  partyLabel: text("party_label"),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const policyCounters = pgTable("policy_counters", {
  projectId: text("project_id").notNull(),
  scope: text("scope").notNull(),
  key: text("key").notNull(),
  n: integer("n").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const portalLinks = pgTable("portal_links", {
  hash: text("hash").primaryKey(),
  projectId: text("project_id").notNull(),
  clientId: text("client_id").notNull(),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
  used: boolean("used").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  usedAt: bigint("used_at", { mode: "number" }),
  sessionToken: text("session_token"),
});

export const portalSessions = pgTable("portal_sessions", {
  token: text("token").primaryKey(),
  projectId: text("project_id").notNull(),
  clientId: text("client_id").notNull(),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const projects = pgTable("projects", {
  id: text("id").primaryKey(),
  orgId: text("org_id").notNull(),
  name: text("name").notNull(),
  wedges: jsonb("wedges").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  slug: text("slug"),
  customDomain: text("custom_domain"),
  domainVerifyToken: text("domain_verify_token"),
  customDomainVerifiedAt: timestamp("custom_domain_verified_at", { withTimezone: true }),
  branding: jsonb("branding"),
  domainProvisioning: jsonb("domain_provisioning"),
});

export const publishedPages = pgTable("published_pages", {
  token: text("token").primaryKey(),
  id: text("id").notNull(),
  projectId: text("project_id").notNull(),
  html: text("html").notNull(),
  title: text("title").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const records = pgTable("records", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  wedge: text("wedge").notNull(),
  collection: text("collection").notNull(),
  key: text("key").notNull(),
  data: jsonb("data").notNull(),
  caseId: uuid("case_id"),
  observedAt: text("observed_at").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const rules = pgTable("rules", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  wedge: text("wedge").notNull(),
  clientId: text("client_id"),
  sensitivity: text("sensitivity"),
  taskTypes: jsonb("task_types").notNull(),
  subject: text("subject").notNull(),
  text: text("text").notNull(),
  kind: text("kind").notNull(),
  status: text("status").notNull(),
  supersededBy: text("superseded_by"),
  corroborations: integer("corroborations").notNull(),
  correctionsSince: integer("corrections_since").notNull(),
  uses: integer("uses").notNull(),
  needsReview: boolean("needs_review").notNull(),
  provenance: jsonb("provenance").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const schedules = pgTable("schedules", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  name: text("name").notNull(),
  wedge: text("wedge").notNull(),
  taskType: text("task_type").notNull(),
  input: jsonb("input").notNull(),
  cadence: jsonb("cadence").notNull(),
  enabled: boolean("enabled").notNull(),
  nextRunAt: timestamp("next_run_at", { withTimezone: true }).notNull(),
  lastRunAt: timestamp("last_run_at", { withTimezone: true }),
  lastTaskId: uuid("last_task_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const secrets = pgTable("secrets", {
  key: text("key").primaryKey(),
  v: integer("v").notNull(),
  kid: text("kid").notNull(),
  iv: text("iv").notNull(),
  tag: text("tag").notNull(),
  ct: text("ct").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const sessions = pgTable("sessions", {
  tokenHash: text("token_hash").primaryKey(),
  memberId: text("member_id").notNull(),
  orgId: text("org_id").notNull(),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
});

export const signatureEnvelopes = pgTable("signature_envelopes", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  clientId: text("client_id"),
  caseId: text("case_id"),
  title: text("title").notNull(),
  document: jsonb("document").notNull(),
  signers: jsonb("signers").notNull(),
  status: text("status").notNull(),
  createdAt: text("created_at").notNull(),
  sentAt: text("sent_at"),
  completedAt: text("completed_at"),
  expiresAt: text("expires_at").notNull(),
  voidedReason: text("voided_reason"),
  onExecute: jsonb("on_execute"),
});

export const signupAccess = pgTable("signup_access", {
  id: text("id").primaryKey(),
  email: text("email"),
  note: text("note"),
  invitedBy: text("invited_by").notNull(),
  tokenHash: text("token_hash"),
  expiresAt: bigint("expires_at", { mode: "number" }),
  usedAt: timestamp("used_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const signupRequests = pgTable("signup_requests", {
  email: text("email").primaryKey(),
  source: text("source"),
  about: text("about"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull(),
  grantedAt: timestamp("granted_at", { withTimezone: true }),
});

export const tasks = pgTable("tasks", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  caseId: uuid("case_id"),
  wedge: text("wedge").notNull(),
  taskType: text("task_type").notNull(),
  actor: jsonb("actor").notNull(),
  input: jsonb("input").notNull(),
  constraints: jsonb("constraints").notNull(),
  tools: jsonb("tools").notNull(),
  outputSchema: jsonb("output_schema"),
  status: text("status").notNull(),
  error: text("error"),
  costUsd: numeric("cost_usd").notNull(),
  eventSeq: integer("event_seq").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  clientId: text("client_id"),
  source: text("source"),
  assignedTo: text("assigned_to"),
  confidenceScore: doublePrecision("confidence_score"),
  batchId: text("batch_id"),
});

export const threads = pgTable("threads", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  clientId: uuid("client_id").notNull(),
  channelId: uuid("channel_id").notNull(),
  subject: text("subject"),
  status: text("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  caseId: uuid("case_id"),
});

export const triggerSubs = pgTable("trigger_subs", {
  id: uuid("id").primaryKey(),
  projectId: text("project_id"),
  connectionId: uuid("connection_id").notNull(),
  triggerSlug: text("trigger_slug").notNull(),
  triggerId: text("trigger_id"),
  owner: jsonb("owner").notNull(),
  wedge: text("wedge").notNull(),
  taskType: text("task_type").notNull(),
  config: jsonb("config").notNull(),
  enabled: boolean("enabled").notNull(),
  lastEventAt: timestamp("last_event_at", { withTimezone: true }),
  lastTaskId: uuid("last_task_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});
